# Pre-commit hooks for formatting and validation
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/prettier/prettier
    rev: v3.0.0
    hooks:
      - id: prettier
        files: "\\.(js|ts|json|md)$"
