name: ✍️ Signature Check

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check commit signatures
        run: |
          git log --pretty=format:'%G? %h %s' | grep -v '^G'
