name: Verified Commit Example

on:
  push:
    branches:
      - '*'           # Runs on all branches
  pull_request:
    branches:
      - '*'           # Runs on all branches

jobs:
  verified-commit-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Commit file
        uses: tohgarashi/verified-commit@v2.x
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: myfile
          commit-message: Committing ./myfile
          ref: ${{ github.ref }}   # Commits to the current branch

      - name: Commit multiple files
        uses: tohgarashi/verified-commit@v2.x
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            path/to/myfile1
            path/to/myfile2
            path/to/myfile3
          commit-message: Committing files
          ref: ${{ github.ref }}

      - name: Auto-detect changed files and commit
        uses: tohgarashi/verified-commit@v2.x
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          detect-changed: true
          commit-message: Committing detected changed files
          ref: ${{ github.ref }}
